/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Zuumb": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ZuumbApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ZuumbWebSocketApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "Zuumbdb": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
